# Generated by Django 6.0.5 on 2026-05-17 19:38

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Clase CSS del ícono', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categoría de proyecto',
                'verbose_name_plural': 'Categorías de proyectos',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProyectoEnProgreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título del proyecto')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('description', models.TextField(verbose_name='Descripción del proyecto')),
                ('estado', models.CharField(choices=[('PLANIFICACION', 'En planificación'), ('EN_CURSO', 'En curso'), ('PAUSADO', 'Pausado'), ('CASI_COMPLETADO', 'Casi completado')], default='PLANIFICACION', max_length=20)),
                ('urgencia', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('CRITICA', 'Crítica')], default='MEDIA', max_length=20)),
                ('start_date', models.DateField(verbose_name='Fecha de inicio')),
                ('estimated_end_date', models.DateField(blank=True, null=True, verbose_name='Fecha estimada de finalización')),
                ('location', models.CharField(max_length=200, verbose_name='Ubicación')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('meta_donacion', models.DecimalField(decimal_places=2, default=0, help_text='Monto total necesario para el proyecto', max_digits=12, verbose_name='Meta de donación ($)')),
                ('recaudado', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Monto recaudado ($)')),
                ('necesidades', models.TextField(help_text='Qué necesita el proyecto (materiales, fondos, voluntarios, etc.)', verbose_name='Necesidades del proyecto')),
                ('voluntarios_necesarios', models.PositiveIntegerField(default=0)),
                ('voluntarios_actuales', models.PositiveIntegerField(default=0)),
                ('cover_image', models.ImageField(upload_to='proyectos/progreso/cover/%Y/', verbose_name='Imagen de portada')),
                ('video_url', models.URLField(blank=True, verbose_name='Video promocional')),
                ('avance_porcentaje', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='% de avance')),
                ('donacion_destacada_monto', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Donación destacada')),
                ('donacion_destacada_nombre', models.CharField(blank=True, max_length=200, verbose_name='Nombre del donante destacado')),
                ('views', models.PositiveIntegerField(default=0)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos_progreso', to='proyectos.categoriaproyecto')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_proyectos_progreso', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Proyecto en progreso',
                'verbose_name_plural': 'Proyectos en progreso',
                'ordering': ['-urgencia', '-avance_porcentaje', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NecesidadEspecifica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ECONOMICA', 'Económica'), ('MATERIAL', 'Material'), ('VOLUNTARIADO', 'Voluntariado'), ('EQUIPO', 'Equipo'), ('INFRAESTRUCTURA', 'Infraestructura'), ('OTRO', 'Otro')], max_length=20)),
                ('descripcion', models.TextField()),
                ('cantidad_necesaria', models.PositiveIntegerField(default=1)),
                ('cantidad_cubierta', models.PositiveIntegerField(default=0)),
                ('es_urgente', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='necesidades_especificas', to='proyectos.proyectoenprogreso')),
            ],
            options={
                'verbose_name': 'Necesidad específica',
                'verbose_name_plural': 'Necesidades específicas',
                'ordering': ['order', '-es_urgente'],
            },
        ),
        migrations.CreateModel(
            name='GaleriaProyectoProgreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='proyectos/progreso/galeria/%Y/')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galeria', to='proyectos.proyectoenprogreso')),
            ],
            options={
                'verbose_name': 'Imagen de galería',
                'verbose_name_plural': 'Galería de imágenes',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ActualizacionProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='proyectos/progreso/updates/%Y/')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyecto_actualizaciones', to=settings.AUTH_USER_MODEL)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actualizaciones', to='proyectos.proyectoenprogreso')),
            ],
            options={
                'verbose_name': 'Actualización de proyecto',
                'verbose_name_plural': 'Actualizaciones de proyectos',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='ProyectoRealizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título del proyecto')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('description', models.TextField(verbose_name='Descripción del proyecto')),
                ('start_date', models.DateField(verbose_name='Fecha de inicio')),
                ('end_date', models.DateField(verbose_name='Fecha de finalización')),
                ('location', models.CharField(max_length=200, verbose_name='Ubicación')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('impacto_nivel', models.CharField(choices=[('BAJO', 'Impacto Bajo'), ('MEDIO', 'Impacto Medio'), ('ALTO', 'Impacto Alto'), ('MUY_ALTO', 'Impacto Muy Alto')], default='MEDIO', max_length=20)),
                ('beneficiarios', models.PositiveIntegerField(default=0, help_text='Cantidad de personas beneficiadas', verbose_name='Número de beneficiarios')),
                ('voluntarios', models.PositiveIntegerField(default=0, verbose_name='Voluntarios participantes')),
                ('inversion_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Inversión total ($)')),
                ('cover_image', models.ImageField(upload_to='proyectos/realizados/cover/%Y/', verbose_name='Imagen de portada')),
                ('video_url', models.URLField(blank=True, verbose_name='Video destacado (YouTube/Vimeo)')),
                ('views', models.PositiveIntegerField(default=0)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos_realizados', to='proyectos.categoriaproyecto')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_proyectos_realizados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Proyecto realizado',
                'verbose_name_plural': 'Proyectos realizados',
                'ordering': ['-end_date', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ImagenAntesDespues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image_before', models.ImageField(upload_to='proyectos/realizados/antes/%Y/', verbose_name='Imagen ANTES')),
                ('image_after', models.ImageField(upload_to='proyectos/realizados/despues/%Y/', verbose_name='Imagen DESPUÉS')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes_antes_despues', to='proyectos.proyectorealizado')),
            ],
            options={
                'verbose_name': 'Imagen Antes/Después',
                'verbose_name_plural': 'Imágenes Antes/Después',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='GaleriaProyectoRealizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='proyectos/realizados/galeria/%Y/')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galeria', to='proyectos.proyectorealizado')),
            ],
            options={
                'verbose_name': 'Imagen de galería',
                'verbose_name_plural': 'Galería de imágenes',
                'ordering': ['order'],
            },
        ),
    ]
