# Generated by Django 6.0.5 on 2026-05-17 19:24

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(help_text='Nombre de la persona que da el testimonio', max_length=100, verbose_name='Nombre del autor')),
                ('author_email', models.EmailField(help_text='Para contacto interno, no se muestra públicamente', max_length=254, verbose_name='Email del autor')),
                ('author_type', models.CharField(choices=[('DONANTE', 'Donante'), ('VOLUNTARIO', 'Voluntario'), ('BENEFICIARIO', 'Beneficiario'), ('ALIADO', 'Aliado estratégico'), ('PARTICIPANTE', 'Participante')], default='PARTICIPANTE', max_length=20, verbose_name='Tipo de autor')),
                ('title', models.CharField(blank=True, help_text='Opcional: título corto del testimonio', max_length=200, verbose_name='Título')),
                ('content', models.TextField(help_text='Testimonio completo (mínimo 20 caracteres, máximo 2000)', validators=[django.core.validators.MinLengthValidator(20), django.core.validators.MaxLengthValidator(2000)], verbose_name='Contenido')),
                ('author_photo', models.ImageField(blank=True, null=True, upload_to='testimonios/photos/%Y/%m/', verbose_name='Foto del autor')),
                ('video_url', models.URLField(blank=True, help_text='URL del video de testimonio', verbose_name='Video testimonio (YouTube/Vimeo)')),
                ('proyecto_nombre', models.CharField(blank=True, help_text='Nombre del proyecto relacionado (temporal)', max_length=200, null=True, verbose_name='Proyecto relacionado')),
                ('rating', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 estrellas'), (2, '2 estrellas'), (3, '3 estrellas'), (4, '4 estrellas'), (5, '5 estrellas')], help_text='Calificación de 1 a 5 estrellas', null=True, verbose_name='Calificación')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente de revisión'), ('APPROVED', 'Aprobado'), ('REJECTED', 'Rechazado'), ('FEATURED', 'Destacado')], default='PENDING', max_length=20, verbose_name='Estado')),
                ('rejection_reason', models.TextField(blank=True, help_text='Si es rechazado, indicar el motivo', verbose_name='Motivo de rechazo')),
                ('moderation_notes', models.TextField(blank=True, help_text='Notas internas del moderador', verbose_name='Notas de moderación')),
                ('moderated_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de moderación')),
                ('featured_until', models.DateTimeField(blank=True, help_text='Fecha hasta la cual el testimonio aparecerá como destacado', null=True, verbose_name='Destacado hasta')),
                ('featured_order', models.PositiveIntegerField(default=0, verbose_name='Orden en destacados')),
                ('likes', models.PositiveIntegerField(default=0, verbose_name='Me gusta')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Vistas')),
                ('report_count', models.PositiveIntegerField(default=0, help_text='Número de veces que ha sido reportado', verbose_name='Reportes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de publicación')),
                ('show_author_name', models.BooleanField(default=True, verbose_name='Mostrar nombre del autor')),
                ('show_author_photo', models.BooleanField(default=True, verbose_name='Mostrar foto del autor')),
                ('allow_comments', models.BooleanField(default=False, verbose_name='Permitir comentarios')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_testimonios', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('moderated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_testimonios', to=settings.AUTH_USER_MODEL, verbose_name='Moderado por')),
            ],
            options={
                'verbose_name': 'Testimonio',
                'verbose_name_plural': 'Testimonios',
                'db_table': 'testimonios',
                'ordering': ['-featured_order', '-published_at', '-created_at'],
                'permissions': [('can_moderate_testimonios', 'Puede moderar testimonios'), ('can_feature_testimonios', 'Puede destacar testimonios')],
            },
        ),
        migrations.CreateModel(
            name='TestimonioComentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=500)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('is_approved', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('testimonio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='testimonios.testimonio')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonio_comentarios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comentario de testimonio',
                'verbose_name_plural': 'Comentarios de testimonios',
                'db_table': 'testimonios_comentarios',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestimonioReporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('SPAM', 'Spam'), ('OFFENSIVE', 'Contenido ofensivo'), ('FALSE', 'Información falsa'), ('COPYRIGHT', 'Infracción de derechos'), ('OTHER', 'Otro')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_reports', to=settings.AUTH_USER_MODEL)),
                ('testimonio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='testimonios.testimonio')),
            ],
            options={
                'verbose_name': 'Reporte de testimonio',
                'verbose_name_plural': 'Reportes de testimonios',
                'db_table': 'testimonios_reports',
            },
        ),
        migrations.AddIndex(
            model_name='testimonio',
            index=models.Index(fields=['status', '-published_at'], name='testimonios_status_d35cb0_idx'),
        ),
        migrations.AddIndex(
            model_name='testimonio',
            index=models.Index(fields=['author_type'], name='testimonios_author__30129b_idx'),
        ),
        migrations.AddIndex(
            model_name='testimonio',
            index=models.Index(fields=['status', 'featured_order'], name='testimonios_status_b8ef63_idx'),
        ),
        migrations.AddIndex(
            model_name='testimonio',
            index=models.Index(fields=['-created_at'], name='testimonios_created_324eb0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='testimonioreporte',
            unique_together={('testimonio', 'reported_by')},
        ),
    ]
