# Generated by Django 6.0.5 on 2026-05-19 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonio',
            name='author_email',
            field=models.EmailField(blank=True, help_text='Para contacto interno, no se muestra públicamente', max_length=254, null=True, verbose_name='Email del autor'),
        ),
    ]
