# Generated by Django 5.2.14 on 2026-05-17 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteText',
            fields=[
                ('key', models.SlugField(max_length=64, primary_key=True, serialize=False)),
                ('value', models.JSONField(blank=True, default=dict)),
                ('label', models.CharField(blank=True, default='', max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
    ]
