# Generated by Django 5.2.14 on 2026-05-17 19:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_mxn', models.PositiveIntegerField()),
                ('frequency', models.CharField(choices=[('once', 'Una vez'), ('monthly', 'Mensual'), ('yearly', 'Anual')], max_length=10)),
                ('destination', models.CharField(blank=True, default='', max_length=120)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('succeeded', 'Completada'), ('failed', 'Fallida'), ('refunded', 'Reembolsada')], default='pending', max_length=12)),
                ('donor_name', models.CharField(blank=True, default='', max_length=120)),
                ('donor_email', models.EmailField(blank=True, default='', max_length=254)),
                ('donor_phone', models.CharField(blank=True, default='', max_length=32)),
                ('donor_rfc', models.CharField(blank=True, default='', max_length=16)),
                ('stripe_payment_intent_id', models.CharField(blank=True, default='', max_length=64)),
                ('stripe_client_secret', models.CharField(blank=True, default='', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
